apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka-cluster
  labels:
    app: kafka
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  selector:
    name: kafka
  type: LoadBalancer
