kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka-deployment
  namespace: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka
  template:
    metadata:
      labels:
        name: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "32547"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: internal-a3a239e12ce1911e6b8cc029664e477e-1763884073.us-west-2.elb.amazonaws.com
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181,zoo2:2181,zoo3:2181
        - name: KAFKA_CREATE_TOPICS
          value: mytopic:2:1
